// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/23/2025, 10:49:25 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/MANH HOANG/Desktop/nustjs/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/MANH HOANG/Desktop/nustjs/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/MANH HOANG/Desktop/nustjs/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/MANH HOANG/Desktop/nustjs/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/MANH HOANG/Desktop/nustjs/plugins/**/*.{js,ts,mjs}","C:/Users/MANH HOANG/Desktop/nustjs/composables/**/*.{js,ts,mjs}","C:/Users/MANH HOANG/Desktop/nustjs/utils/**/*.{js,ts,mjs}","C:/Users/MANH HOANG/Desktop/nustjs/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/MANH HOANG/Desktop/nustjs/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/MANH HOANG/Desktop/nustjs/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/MANH HOANG/Desktop/nustjs/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["darkMode"] = ["selector","[class~=\"dark-mode\"]"];;return cfg;})();

export default resolvedConfig;