// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/18/2025, 11:50:05 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/MANH HOANG/Desktop/FE/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/MANH HOANG/Desktop/FE/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/MANH HOANG/Desktop/FE/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/MANH HOANG/Desktop/FE/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/MANH HOANG/Desktop/FE/plugins/**/*.{js,ts,mjs}","C:/Users/MANH HOANG/Desktop/FE/composables/**/*.{js,ts,mjs}","C:/Users/MANH HOANG/Desktop/FE/utils/**/*.{js,ts,mjs}","C:/Users/MANH HOANG/Desktop/FE/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/MANH HOANG/Desktop/FE/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/MANH HOANG/Desktop/FE/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/MANH HOANG/Desktop/FE/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["darkMode"] = ["selector","[class~=\"dark-mode\"]"];;return cfg;})();

export default resolvedConfig;