// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/12/2025, 10:51:04 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/hoangvm/Desktop/fe/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hoangvm/Desktop/fe/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hoangvm/Desktop/fe/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hoangvm/Desktop/fe/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hoangvm/Desktop/fe/plugins/**/*.{js,ts,mjs}","C:/Users/hoangvm/Desktop/fe/composables/**/*.{js,ts,mjs}","C:/Users/hoangvm/Desktop/fe/utils/**/*.{js,ts,mjs}","C:/Users/hoangvm/Desktop/fe/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hoangvm/Desktop/fe/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hoangvm/Desktop/fe/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hoangvm/Desktop/fe/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["darkMode"] = ["selector","[class~=\"dark-mode\"]"];;return cfg;})();

export default resolvedConfig;